### ISSUE TITLE
Scalac error in IntelliJ when using scapegoat as a compiler plugin in a maven project

### ISSUE THREAD

**Issue by rigoford** [sksamuel/scalac-scapegoat-plugin#98]
I'm trying to use the scalac-scapegoat-plugin within a very simple maven project (one class and one test) with the following config in the pom.xml:

```xml
	<build>
		<sourceDirectory>${basedir}/src/main/scala</sourceDirectory>
		<testSourceDirectory>${basedir}/src/test/scala</testSourceDirectory>
		<plugins>
			<plugin>
				<groupId>net.alchim31.maven</groupId>
				<artifactId>scala-maven-plugin</artifactId>
				<version>${maven.plugin.scala.version}</version>
				<configuration>
					<scalaCompatVersion>${scala.major.version}</scalaCompatVersion>
					<scalaVersion>${scala.version}</scalaVersion>
					<dependencies>
						<dependency>
							<groupId>com.sksamuel.scapegoat</groupId>
							<artifactId>scalac-scapegoat-plugin_${scala.major.version}</artifactId>
							<version>${scalac.plugin.scapegoat.version}</version>
						</dependency>
					</dependencies>
					<compilerPlugins>
						<compilerPlugin>
							<groupId>com.sksamuel.scapegoat</groupId>
							<artifactId>scalac-scapegoat-plugin_${scala.major.version}</artifactId>
							<version>${scalac.plugin.scapegoat.version}</version>
						</compilerPlugin>
					</compilerPlugins>
					<args>
						<arg>-P:scapegoat:dataDir:target</arg>
						<arg>-P:scapegoat:consoleOutput:true</arg>
					</args>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>compile</goal>
							<goal>testCompile</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
```
(appropriate properties having been set).

Running `mvn clean verify` from the command line or within IntelliJ (v14.0.3) gives expected output, however if I then try to run the test from within IntelliJ (i.e. `Run 'MyClassSpec'`) the compilation fails with the following error:

```
Error:scalac: Error: object com.sksamuel.scapegoat.Safe in compiler mirror not found.
scala.ScalaReflectionException: object com.sksamuel.scapegoat.Safe in compiler mirror not found.
	at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:123)
	at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:22)
	at com.sksamuel.scapegoat.InspectionContext$Traverser$$typecreator2$1.apply(Inspection.scala:49)
	at scala.reflect.api.TypeTags$WeakTypeTagImpl.tpe$lzycompute(TypeTags.scala:232)
	at scala.reflect.api.TypeTags$WeakTypeTagImpl.tpe(TypeTags.scala:232)
	at scala.reflect.api.TypeTags$class.typeOf(TypeTags.scala:341)
	at scala.reflect.api.Universe.typeOf(Universe.scala:61)
	at com.sksamuel.scapegoat.InspectionContext$Traverser$class.$init$(Inspection.scala:49)
	at com.sksamuel.scapegoat.inspections.collections.ArrayEquals$$anon$2$$anon$1.<init>(ArrayEquals.scala:9)
	at com.sksamuel.scapegoat.inspections.collections.ArrayEquals$$anon$2.postTyperTraverser(ArrayEquals.scala:9)
	at com.sksamuel.scapegoat.inspections.collections.ArrayEquals$$anon$2.postTyperTraverser(ArrayEquals.scala:8)
	at com.sksamuel.scapegoat.ScapegoatComponent$Transformer$$anonfun$transform$2.apply(plugin.scala:126)
	at com.sksamuel.scapegoat.ScapegoatComponent$Transformer$$anonfun$transform$2.apply(plugin.scala:124)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.sksamuel.scapegoat.ScapegoatComponent$Transformer.transform(plugin.scala:124)
	at com.sksamuel.scapegoat.ScapegoatComponent$Transformer.transform(plugin.scala:113)
	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:147)
	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:428)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:419)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:428)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:386)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:386)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1195)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:386)
	at com.sksamuel.scapegoat.ScapegoatComponent$$anon$1.run(plugin.scala:87)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1338)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1325)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1320)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1418)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:126)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:102)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:102)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:48)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:29)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:26)
	at org.jetbrains.jps.incremental.scala.remote.Main$.make(Main.scala:62)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:20)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
```

Do you have any idea what the issue may be? I can provide the simple project if necessary.

Many thanks

Martin

**Comment by rigoford** [comment]
If I add the com.sksamuel.scapegoat:scalac-scapegoat-plugin_2.11 dependency as a 'normal' maven dependency and not a compiler dependency I do not get the

"Error:scalac: Error: object com.sksamuel.scapegoat.Safe in compiler mirror not found. scala.ScalaReflectionException: object com.sksamuel.scapegoat.Safe in compiler mirror not found."

error, however I do get a similar error for a scala-xml class. Adding this as a normal maven dependency removes that error and IntelliJ seems to build the project and run the test fine.  Although I'm not convinced of the stability of this.

Looking at the scala-maven-plugin [documentation](http://davidb.github.io/scala-maven-plugin/example_scalac_plugins.html), it recommends that:

"A scalac plugin should only have dependencies on the scala-compiler artifact, and these dependencies should be of type "provided"."

It seems that this is the source of the issue.

**Comment by mauhiz** [comment]
having the same error with a different setup:

- sbt with sub-projects
- compilerPlugin("com.sksamuel.scapegoat" %% "scalac-scapegoat-plugin" % "0.94.6")

any idea?

**Comment by rigoford** [comment]
I raised this with JetBrains, https://youtrack.jetbrains.com/issue/SCL-8344. Basically the solution (workaround) is to add scapegoat as a dependency.
